#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Normalise Orca G-code for diffing: drop the header block, the trailing CONFIG block and volatile comments.

    normalize_gcode.py in.gcode out.gcode

Derived from the Phase 0 spike (spike/tools/normalize_gcode.py). Used by the golden comparison against the official
OrcaSlicer release at the pinned tag (02 section 8, item 3).
"""
from __future__ import annotations

import re
import sys

_VOLATILE = re.compile(
    r"^; (generated by|total estimated time|estimated printing time|model printing time|filament used|total filament|"
    r"total layers|total cost|ext #)", re.I)
_TIME = re.compile(r"^;\s*(Time|TIME|time|PRINTING_TIME)")


def normalize(text: str) -> list[str]:
    out: list[str] = []
    skip = None
    for line in text.splitlines():
        s = line.rstrip("\r\n")
        if s.startswith("; HEADER_BLOCK_START"):
            skip = "; HEADER_BLOCK_END"
            continue
        if s.startswith("; CONFIG_BLOCK_START"):
            skip = "; CONFIG_BLOCK_END"
            continue
        if skip:
            if s.startswith(skip):
                skip = None
            continue
        if _VOLATILE.match(s) or _TIME.match(s):
            continue
        out.append(s)
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    with open(argv[0], errors="replace") as f:
        lines = normalize(f.read())
    with open(argv[1], "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(argv[1], len(lines), "lines")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
