#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Normalise Orca G-code for diffing: drop the header block and volatile comments; keep the trailing CONFIG
block except for the keys in CONFIG_KNOWN_DIFFERENCES.

    normalize_gcode.py in.gcode out.gcode

Derived from the Phase 0 spike (spike/tools/normalize_gcode.py). Used by the golden comparison against the official
OrcaSlicer release at the pinned tag (02 section 8, item 3).
"""
from __future__ import annotations

import re
import sys

_VOLATILE = re.compile(
    r"^; (generated by|total estimated time|estimated printing time|model printing time|filament used|total filament|"
    r"total layers|total cost|ext #)", re.I)

# Keys of the trailing CONFIG block that differ between our output and the official CLI's for the golden cube
# (found by diffing the two blocks, 2026-10-10). Everything else in the block is compared, so a changed setting
# fails the golden comparison. Each group says why it differs; a key that stops differing is a stale entry and
# fails stale_known_differences() (tests/binding/test_run_cube.py), so the list can only shrink.
CONFIG_KNOWN_DIFFERENCES: dict[str, str] = {
    # The CLI loads JSON profiles straight into the config; compose_config builds full presets, which adds keys
    # the profiles do not carry (their defaults, never consumed by the G-code generator).
    **{k: "default added by compose_config, not in the profile set the CLI loads" for k in (
        "bbl_use_printhost", "default_bed_type", "default_filament_profile", "default_nozzle_volume_type",
        "extruder_variant_list", "filament_colour_type", "filament_multi_colour", "filament_retract_lift_above",
        "filament_retract_lift_below", "filament_retract_lift_enforce", "flashforge_serial_number", "host_type",
        "ironing_expansion", "pellet_flow_coefficient", "pellet_modded_printer", "printer_agent",
        "printhost_authorization_type", "printhost_ssl_ignore_revoke", "thumbnails_format",
        "upward_compatible_machine")},
    # Preset provenance, not print behaviour.
    **{k: "preset provenance metadata" for k in (
        "different_settings_to_system", "inherits_group", "print_compatible_printers", "filament_ids")},
    "thumbnails": "list separator spacing (', ' vs ',') in the serialized value",
}
_CONFIG_LINE = re.compile(r"^; ([A-Za-z0-9_]+) = ")
_TIME = re.compile(r"^;\s*(Time|TIME|time|PRINTING_TIME)")


def config_block(text: str) -> dict[str, str]:
    """The `; key = value` lines between CONFIG_BLOCK_START and CONFIG_BLOCK_END, as a dict."""
    out: dict[str, str] = {}
    in_config = False
    for line in text.splitlines():
        s = line.rstrip("\r\n")
        if s.startswith("; CONFIG_BLOCK_START"):
            in_config = True
        elif s.startswith("; CONFIG_BLOCK_END"):
            in_config = False
        elif in_config:
            m = re.match(r"^; ([A-Za-z0-9_]+) = (.*)$", s)
            if m:
                out[m.group(1)] = m.group(2)
    return out


def stale_known_differences(got_text: str, reference_text: str) -> list[str]:
    """Entries of CONFIG_KNOWN_DIFFERENCES that no longer differ: the key has the same value in both CONFIG blocks
    (or is in neither). They must be removed, so an entry cannot hide a regression after the cause is fixed."""
    got, ref = config_block(got_text), config_block(reference_text)
    return sorted(k for k in CONFIG_KNOWN_DIFFERENCES if got.get(k) == ref.get(k))


def normalize(text: str) -> list[str]:
    out: list[str] = []
    skip = None
    in_config = False
    for line in text.splitlines():
        s = line.rstrip("\r\n")
        if s.startswith("; HEADER_BLOCK_START"):
            skip = "; HEADER_BLOCK_END"
            continue
        if s.startswith("; CONFIG_BLOCK_START"):
            in_config = True
        elif s.startswith("; CONFIG_BLOCK_END"):
            in_config = False
        elif in_config:
            m = _CONFIG_LINE.match(s)
            if m and m.group(1) in CONFIG_KNOWN_DIFFERENCES:
                continue
        if skip:
            if s.startswith(skip):
                skip = None
            continue
        if _VOLATILE.match(s) or _TIME.match(s):
            continue
        out.append(s)
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    with open(argv[0], errors="replace") as f:
        lines = normalize(f.read())
    with open(argv[1], "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(argv[1], len(lines), "lines")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
