# SPDX-License-Identifier: AGPL-3.0-only
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))
import normalize_gcode as ng  # noqa: E402


def gcode(**cfg):
    lines = ["; HEADER_BLOCK_START", "; generated by X", "; HEADER_BLOCK_END", "G1 X1", "; CONFIG_BLOCK_START"]
    lines += [f"; {k} = {v}" for k, v in cfg.items()]
    lines += ["; CONFIG_BLOCK_END"]
    return "\n".join(lines)


def test_config_block_is_read_between_the_markers():
    text = "; a = 1\n" + gcode(layer_height="0.2", thumbnails="48x48/PNG") + "\n; b = 2"
    assert ng.config_block(text) == {"layer_height": "0.2", "thumbnails": "48x48/PNG"}


def test_an_allowlisted_key_that_no_longer_differs_is_stale():
    key = next(iter(ng.CONFIG_KNOWN_DIFFERENCES))
    differs = ng.stale_known_differences(gcode(**{key: "ours"}), gcode(**{key: "theirs"}))
    assert key not in differs
    same = ng.stale_known_differences(gcode(**{key: "x"}), gcode(**{key: "x"}))
    assert key in same
    only_ours = ng.stale_known_differences(gcode(**{key: "x"}), gcode(layer_height="0.2"))
    assert key not in only_ours  # present on one side only is a difference
    assert key in ng.stale_known_differences(gcode(), gcode())  # absent on both sides: stale


def test_known_differences_are_dropped_from_the_normalised_config_block():
    key = next(iter(ng.CONFIG_KNOWN_DIFFERENCES))
    out = ng.normalize(gcode(**{key: "x", "layer_height": "0.2"}))
    assert "; layer_height = 0.2" in out and f"; {key} = x" not in out
