# SPDX-License-Identifier: AGPL-3.0-only
# slicewright_engine/__init__.pyi — API 1.0 (the stub in engine/python/ is generated from this block)
import numpy as np
from numpy.typing import NDArray

API_VERSION: tuple[int, int] = (1, 0)

def version() -> dict: ...
#  {"version": "1.0.0",                # engine package version (PEP 440)
#   "api": (1, 0),                     # == API_VERSION
#   "orca_tag": "v2.x.y", "orca_commit": "<40-hex>",
#   "patches": ["0001-headless-minimal", ...],
#   "build": {"compiler": str, "platform": "macos-arm64"|"windows-x64"|"linux-x64",
#             "date": "YYYY-MM-DD", "deps": {"boost": "1.84.0", ...}},
#   "source_url": "https://github.com/<owner>/<repo>/releases/tag/engine-v1.0.0"}

def enums() -> dict[str, dict[str, int]]: ...
#  {"move_type": {"Noop": 0, ..., "Extrude": 10}, "role": {"None": 0, ..., "Mixed": 19}}
#  Guaranteed: every move_type value < 16 and every role value < 32.

def config_schema() -> dict[str, dict]: ...          # §6.4
def tab_layout() -> dict[str, list[dict]]: ...       # §6.5
def profiles_archive() -> str: ...                   # path of profiles.zip inside the wheel (read-only; read with zipfile, 02 §7.1)
def resources_dir() -> str: ...                      # read-only, inside the wheel
def licenses() -> dict[str, str]: ...                # {"LICENSE", "THIRD_PARTY_LICENSES", "NOTICE", "SOURCE"} -> text
def set_log(level: int, path: str | None = None) -> None: ...
#  level 0 fatal … 5 trace (Orca's set_logging_level scale). Default at import: 1 (errors).

def compose_config(printer: dict, process: dict, filaments: list[dict],
                   project: dict[str, str] | None = None, *,
                   collapse_variants: bool = False) -> dict[str, str]: ...        # §6.1
def normalize_config(flat: dict[str, str]) -> dict: ...                           # §6.2
def eval_condition(expr: str, config: dict) -> bool: ...                          # §6.3

class ConditionContext:                                                           # §6.3
    def __init__(self, config: dict) -> None: ...
    def eval(self, expr: str) -> bool: ...

class CancelToken:
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class SliceJob:                                                                   # §4
    def __init__(self) -> None: ...
    def set_config(self, flat: dict[str, str]) -> None: ...
    def set_threads(self, n: int) -> None: ...
    def add_object(self, name: str,
                   vertices: NDArray[np.float32], triangles: NDArray[np.int32], *,
                   extruder: int = 0,
                   config_overrides: dict[str, str] | None = None,
                   face_extruder: NDArray[np.uint8] | None = None,
                   face_support: NDArray[np.uint8] | None = None,
                   face_seam: NDArray[np.uint8] | None = None,
                   repair: bool = False,
                   ensure_on_bed: bool = False) -> int: ...
    def set_thumbnails(self, images: list[NDArray[np.uint8]]) -> None: ...
    def validate(self) -> list[dict]: ...                                         # list[Issue]
    def arrange(self, spacing_mm: float | None = None,
                allow_rotation: bool = False) -> list[dict]: ...                  # list[Placement]
    def start(self) -> None: ...
    def poll(self) -> tuple[str, float, str]: ...
    def cancel(self) -> None: ...
    def result(self, timeout: float | None = None) -> "SliceResult": ...
    def run(self, progress=None, cancel: CancelToken | None = None) -> "SliceResult": ...

class SliceResult:                                                                # §5
    gcode_path: str
    moves: dict[str, NDArray]
    layers: dict[str, NDArray]
    gcode_line_ends: NDArray[np.uint64]
    stats: dict
    warnings: list[dict]                                                          # list[Issue]
    objects: list[str]
    wipe_tower: dict | None
    def write_gcode(self, path: str) -> None: ...
    def write_gcode_3mf(self, path: str, plate_meta: dict | None = None) -> None: ...
    def output_filename(self, input_basename: str) -> str: ...

# Exceptions: §7
class Error(Exception): ...
class Cancelled(Error): ...
class Busy(Error): ...
class StateError(Error): ...
class ConfigError(Error): ...
class ValidationError(Error): ...
class SliceError(Error): ...
class ArrangeError(Error): ...
class EngineError(Error): ...
