# SPDX-License-Identifier: AGPL-3.0-only
"""Normalise Orca G-code for diffing: drop the header block, the trailing CONFIG block and volatile comments.
Usage: normalize_gcode.py in.gcode out.gcode"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
out = []
skip = None
for line in open(src, errors="replace"):
    s = line.rstrip("\r\n")
    if s.startswith("; HEADER_BLOCK_START"):
        skip = "; HEADER_BLOCK_END"
        continue
    if s.startswith("; CONFIG_BLOCK_START"):
        skip = "; CONFIG_BLOCK_END"
        continue
    if skip:
        if s.startswith(skip):
            skip = None
        continue
    if re.match(r"^; (generated by|total estimated time|estimated printing time|model printing time|filament used|total filament|total layers|total cost|ext #)", s, re.I):
        continue
    if re.match(r"^;\s*(Time|TIME|time|PRINTING_TIME)", s):
        continue
    out.append(s)
open(dst, "w", newline="\n").write("\n".join(out) + "\n")
print(dst, len(out), "lines")
