# SPDX-License-Identifier: GPL-3.0-or-later
"""More keys for the fake schema: the options the show/enable rules (03 section 2.4) talk about.

Key names are the public Orca profile format; labels are derived mechanically from the key and the
enum value lists are the serialised values of the public format, so nothing here is copied from
Orca's source or its translated strings. The real schema has ~800 keys; the fake carries just the
ones the add-on's own tests need, so ``test_settings_rules`` can assert "every rule key exists in the
schema" against both backends.
"""
from __future__ import annotations

# (key, type, default, extra) where extra may hold enum=[...], min, max, mode.
# On/off flags per extruder are "ints" holding 0 or 1 (the fake composes only a few vector types).
_GROUPS = {
    ("process", "Strength"): [
        ("infill_combination", "bool", "0", {}),
        ("fill_multiline", "int", "1", {"min": 1, "max": 5}),
        ("infill_direction", "float", "45", {"min": 0, "max": 360}),
        ("minimum_sparse_infill_area", "float", "15", {"min": 0}),
        ("infill_anchor", "floatOrPercent", "400%", {}),
        ("infill_anchor_max", "floatOrPercent", "20", {}),
        ("infill_shift_step", "float", "0.4", {"min": 0}),
        ("symmetric_infill_y_axis", "bool", "0", {}),
        ("top_surface_pattern", "enum", "monotonic", {"enum": ["monotonic", "monotonicline", "rectilinear", "concentric"]}),
        ("bottom_surface_pattern", "enum", "monotonic", {"enum": ["monotonic", "monotonicline", "rectilinear", "concentric"]}),
        ("top_surface_density", "percent", "100%", {"min": 10, "max": 100}),
        ("bottom_surface_density", "percent", "100%", {"min": 10, "max": 100}),
        ("top_layer_direction", "float", "45", {"min": 0, "max": 360, "mode": "advanced"}),
        ("bottom_layer_direction", "float", "45", {"min": 0, "max": 360, "mode": "advanced"}),
        ("top_shell_thickness", "float", "0", {"min": 0}),
        ("bottom_shell_thickness", "float", "0", {"min": 0}),
        ("ensure_vertical_shell_thickness", "bool", "1", {"mode": "advanced"}),
        ("extra_perimeters_on_overhangs", "bool", "0", {"mode": "advanced"}),
        ("detect_thin_wall", "bool", "0", {}),
        ("detect_overhang_wall", "bool", "1", {}),
        ("seam_position", "enum", "aligned", {"enum": ["nearest", "aligned", "back", "random"]}),
        ("staggered_inner_seams", "bool", "0", {"mode": "advanced"}),
        ("wall_sequence", "enum", "inner wall/outer wall", {"enum": ["inner wall/outer wall", "outer wall/inner wall"]}),
        ("wall_generator", "enum", "arachne", {"enum": ["classic", "arachne"]}),
        ("wall_transition_length", "percent", "100%", {"mode": "advanced"}),
        ("wall_transition_filter_deviation", "percent", "25%", {"mode": "advanced"}),
        ("wall_transition_angle", "float", "10", {"mode": "advanced"}),
        ("min_feature_size", "percent", "25%", {"mode": "advanced"}),
        ("min_length_factor", "float", "0.5", {"mode": "advanced"}),
        ("min_bead_width", "percent", "85%", {"mode": "advanced"}),
        ("wall_distribution_count", "int", "1", {"mode": "advanced"}),
        ("initial_layer_min_bead_width", "percent", "85%", {"mode": "advanced"}),
        ("wall_maximum_resolution", "float", "0.5", {"mode": "expert"}),
        ("wall_maximum_deviation", "float", "0.025", {"mode": "expert"}),
        ("outer_wall_line_width", "float", "0.42", {"min": 0}),
        ("spiral_mode", "bool", "0", {}),
        ("spiral_mode_smooth", "bool", "0", {}),
        ("spiral_mode_max_xy_smoothing", "floatOrPercent", "200%", {"mode": "advanced"}),
        ("spiral_starting_flow_ratio", "float", "0", {"mode": "advanced"}),
        ("spiral_finishing_flow_ratio", "float", "0", {"mode": "advanced"}),
    ],
    ("process", "Speed"): [
        ("small_perimeter_speed", "float", "50", {"min": 0}),
        ("small_perimeter_threshold", "float", "0", {"min": 0}),
        ("top_surface_speed", "float", "100", {"min": 0}),
        ("default_acceleration", "float", "5000", {"min": 0}),
        ("outer_wall_acceleration", "float", "3000", {"min": 0}),
        ("inner_wall_acceleration", "float", "5000", {"min": 0}),
        ("initial_layer_acceleration", "float", "500", {"min": 0}),
        ("initial_layer_travel_acceleration", "float", "6000", {"min": 0}),
        ("top_surface_acceleration", "float", "2000", {"min": 0}),
        ("travel_acceleration", "float", "10000", {"min": 0}),
        ("bridge_acceleration", "float", "3000", {"min": 0}),
        ("sparse_infill_acceleration", "floatOrPercent", "100%", {"min": 0}),
        ("default_jerk", "float", "0", {"min": 0}),
        ("outer_wall_jerk", "float", "9", {"min": 0}),
        ("inner_wall_jerk", "float", "9", {"min": 0}),
        ("top_surface_jerk", "float", "9", {"min": 0}),
        ("infill_jerk", "float", "9", {"min": 0}),
        ("initial_layer_jerk", "float", "9", {"min": 0}),
        ("travel_jerk", "float", "12", {"min": 0}),
        ("enable_overhang_speed", "bool", "1", {}),
        ("overhang_1_4_speed", "float", "0", {"min": 0}),
        ("overhang_2_4_speed", "float", "0", {"min": 0}),
        ("overhang_3_4_speed", "float", "0", {"min": 0}),
        ("overhang_4_4_speed", "float", "0", {"min": 0}),
        ("slowdown_for_curled_perimeters", "bool", "0", {"mode": "advanced"}),
    ],
    ("process", "Support"): [
        ("support_type", "enum", "tree(auto)", {"enum": ["normal(auto)", "tree(auto)", "normal(manual)", "tree(manual)"]}),
        ("support_style", "enum", "default", {"enum": ["default", "grid", "snug", "tree_slim", "tree_strong", "tree_hybrid", "tree_organic"]}),
        ("support_threshold_angle", "int", "30", {"min": 0, "max": 90}),
        ("support_on_build_plate_only", "bool", "0", {}),
        ("support_critical_regions_only", "bool", "0", {"mode": "advanced"}),
        ("support_base_pattern", "enum", "default", {"enum": ["default", "rectilinear", "rectilinear-grid", "honeycomb", "lightning", "hollow"]}),
        ("support_base_pattern_spacing", "float", "2.5", {"min": 0}),
        ("support_expansion", "float", "0", {"mode": "advanced"}),
        ("support_angle", "float", "0", {"mode": "advanced"}),
        ("support_top_z_distance", "float", "0.2", {"min": 0}),
        ("support_bottom_z_distance", "float", "0.2", {"min": 0}),
        ("support_object_xy_distance", "float", "0.35", {"min": 0}),
        ("support_object_first_layer_gap", "float", "0.2", {"min": 0, "mode": "advanced"}),
        ("independent_support_layer_height", "bool", "1", {"mode": "advanced"}),
        ("bridge_no_support", "bool", "0", {"mode": "advanced"}),
        ("max_bridge_length", "float", "10", {"min": 0, "mode": "advanced"}),
        ("support_interface_top_layers", "int", "3", {"min": 0}),
        ("support_interface_bottom_layers", "int", "0", {"min": -1}),
        ("support_interface_pattern", "enum", "auto", {"enum": ["auto", "rectilinear", "concentric"]}),
        ("support_interface_spacing", "float", "0.5", {"min": 0}),
        ("support_bottom_interface_spacing", "float", "0.5", {"min": 0, "mode": "advanced"}),
        ("support_interface_loop_pattern", "bool", "0", {"mode": "advanced"}),
        ("support_interface_filament", "int", "0", {"min": 0, "max": 16}),
        ("support_interface_not_for_body", "bool", "1", {"mode": "advanced"}),
        ("support_ironing", "bool", "0", {"mode": "advanced"}),
        ("support_ironing_pattern", "enum", "rectilinear", {"enum": ["rectilinear", "concentric"], "mode": "advanced"}),
        ("support_ironing_flow", "percent", "10%", {"mode": "advanced"}),
        ("support_ironing_spacing", "float", "0.1", {"min": 0, "mode": "advanced"}),
        ("small_support_perimeter_speed", "float", "50", {"min": 0, "mode": "advanced"}),
        ("small_support_perimeter_threshold", "float", "0", {"min": 0, "mode": "advanced"}),
        ("raft_layers", "int", "0", {"min": 0}),
        ("raft_contact_distance", "float", "0.1", {"min": 0}),
        ("raft_first_layer_density", "percent", "90%", {"min": 10, "max": 100}),
    ],
    ("process", "Others"): [
        ("skirt_type", "enum", "combined", {"enum": ["combined", "perobject"]}),
        ("min_skirt_length", "float", "0", {"min": 0}),
        ("skirt_distance", "float", "2", {"min": 0}),
        ("skirt_start_angle", "float", "-135", {}),
        ("skirt_speed", "float", "50", {"min": 0}),
        ("skirt_height", "int", "1", {"min": 1}),
        ("draft_shield", "enum", "disabled", {"enum": ["disabled", "limited", "enabled"]}),
        ("brim_type", "enum", "auto_brim", {"enum": ["auto_brim", "outer_only", "inner_only", "outer_and_inner", "no_brim", "brim_ears"]}),
        ("brim_width", "float", "5", {"min": 0}),
        ("brim_object_gap", "float", "0", {"min": 0}),
        ("brim_ears_max_angle", "float", "125", {"mode": "advanced"}),
        ("brim_ears_detection_length", "float", "1", {"mode": "advanced"}),
        ("ironing_type", "enum", "no ironing", {"enum": ["no ironing", "top", "topmost", "solid"]}),
        ("ironing_pattern", "enum", "zig-zag", {"enum": ["zig-zag", "rectilinear", "concentric"]}),
        ("ironing_flow", "percent", "15%", {}),
        ("ironing_spacing", "float", "0.1", {"min": 0}),
        ("ironing_inset", "float", "0", {"min": 0, "mode": "advanced"}),
        ("ironing_angle", "float", "0", {"mode": "advanced"}),
        ("ironing_angle_fixed", "bool", "0", {"mode": "advanced"}),
        ("ironing_speed", "float", "20", {"min": 0}),
        ("fuzzy_skin", "enum", "none", {"enum": ["none", "external", "all", "allwalls"]}),
        ("fuzzy_skin_mode", "enum", "displacement", {"enum": ["displacement", "extrusion", "combined"]}),
        ("fuzzy_skin_noise_type", "enum", "classic", {"enum": ["classic", "perlin", "billow", "ridgedmulti", "voronoi"]}),
        ("fuzzy_skin_point_distance", "float", "0.8", {"min": 0}),
        ("fuzzy_skin_thickness", "float", "0.3", {"min": 0}),
        ("fuzzy_skin_first_layer", "bool", "0", {"mode": "advanced"}),
        ("seam_slope_type", "enum", "none", {"enum": ["none", "external", "all"]}),
        ("seam_slope_conditional", "bool", "0", {"mode": "advanced"}),
        ("seam_slope_start_height", "floatOrPercent", "0", {"mode": "advanced"}),
        ("seam_slope_entire_loop", "bool", "0", {"mode": "advanced"}),
        ("seam_slope_min_length", "float", "10", {"mode": "advanced"}),
        ("seam_slope_steps", "int", "10", {"mode": "advanced"}),
        ("seam_slope_inner_walls", "bool", "0", {"mode": "advanced"}),
        ("reduce_crossing_wall", "bool", "0", {}),
        ("max_travel_detour_distance", "floatOrPercent", "0", {"mode": "advanced"}),
        ("make_overhang_printable", "bool", "0", {"mode": "advanced"}),
        ("make_overhang_printable_angle", "float", "55", {"mode": "advanced"}),
        ("make_overhang_printable_hole_size", "float", "0", {"mode": "advanced"}),
        ("interlocking_beam", "bool", "0", {"mode": "advanced"}),
        ("interlocking_beam_width", "float", "0.8", {"mode": "advanced"}),
        ("interlocking_orientation", "float", "22.5", {"mode": "advanced"}),
        ("interlocking_beam_layer_count", "int", "2", {"mode": "advanced"}),
        ("interlocking_depth", "float", "3", {"mode": "advanced"}),
        ("interlocking_boundary_avoidance", "float", "2", {"mode": "advanced"}),
        ("mmu_segmented_region_interlocking_depth", "float", "0", {"mode": "advanced"}),
        ("ooze_prevention", "bool", "0", {"mode": "advanced"}),
        ("standby_temperature_delta", "int", "-5", {"mode": "advanced"}),
        ("preheat_time", "float", "30", {"mode": "advanced"}),
    ],
    ("process", "Multimaterial"): [
        ("prime_tower_width", "float", "35", {"min": 2}),
        ("prime_tower_brim_width", "float", "3", {"min": -1}),
        ("prime_tower_skip_points", "bool", "1", {"mode": "advanced"}),
        ("wipe_tower_wall_type", "enum", "rectangle", {"enum": ["rectangle", "cone", "rib"], "mode": "advanced"}),
        ("prime_volume", "float", "45", {"min": 0}),
        ("flush_into_infill", "bool", "0", {"mode": "advanced"}),
        ("flush_into_support", "bool", "1", {"mode": "advanced"}),
        ("flush_into_objects", "bool", "0", {"mode": "advanced"}),
    ],
    ("printer", "Extruder"): [
        ("use_firmware_retraction", "bool", "0", {"mode": "advanced"}),
        ("retraction_length", "floats", "0.8", {"min": 0}),
        ("retraction_speed", "floats", "30", {"min": 0}),
        ("deretraction_speed", "floats", "0", {"min": 0}),
        ("retract_restart_extra", "floats", "0", {"min": 0, "mode": "advanced"}),
        ("retraction_minimum_travel", "floats", "1", {"min": 0}),
        ("z_hop", "floats", "0.4", {"min": 0}),
        ("z_hop_types", "enum", "Normal Lift", {"enum": ["Auto Lift", "Normal Lift", "Slope Lift", "Spiral Lift"]}),
        ("wipe", "ints", "1", {}),
        ("wipe_distance", "floats", "1", {"min": 0}),
    ],
    ("filament", "Cooling"): [
        ("enable_overhang_bridge_fan", "ints", "1", {}),
        ("overhang_fan_speed", "ints", "100", {"min": 0, "max": 100}),
        ("overhang_fan_threshold", "strings", "95%", {}),
        ("slow_down_for_layer_cooling", "ints", "1", {}),
        ("dont_slow_down_outer_wall", "ints", "0", {"mode": "advanced"}),
        ("enable_pressure_advance", "ints", "0", {}),
        ("pressure_advance", "floats", "0.02", {"min": 0}),
    ],
}

# Existing keys the rules also name: the fake enums/ranges the base schema lacks.
EXTRA_ENUM_VALUES = {"sparse_infill_pattern": ["zig-zag", "cross-zag", "locked-zag", "lightning"]}
