# SPDX-License-Identifier: GPL-3.0-or-later
"""Generates the two tiny sample G-code files next to this script.

Both are produced from scratch here (CC0 1.0): a 10 mm square, three layers, with one
quarter-circle corner (a G2 or G3 arc) and one infill line per layer.

* ``plain_square.gcode``: plain Orca-style tags (``;TYPE:`` ...), relative E (M83), G2 arc.
* ``bambu_square.gcode``: Bambu-style tags (``; FEATURE:`` ...), absolute E (M82), G3 arc.

Run ``python make_samples.py`` to regenerate. The output is deterministic.
"""
from __future__ import annotations

import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
FILAMENT_DIAMETER = 1.75
AREA = math.pi * (FILAMENT_DIAMETER / 2) ** 2
WIDTH, HEIGHT = 0.42, 0.2
SIDE, R = 10.0, 2.0   # square side and corner radius, mm
HEADER = """; CC0 1.0 Universal: sample G-code generated by make_samples.py, no rights reserved
; filament_diameter = 1.75
; filament_density = 1.24
"""


def _e(length: float) -> float:
    return WIDTH * HEIGHT * length / AREA


def build(bambu: bool) -> str:
    tags = (dict(role="; FEATURE: ", width="; LINE_WIDTH: ", height="; LAYER_HEIGHT: ",
                 layer="; CHANGE_LAYER") if bambu else
            dict(role=";TYPE:", width=";WIDTH:", height=";HEIGHT:", layer=";LAYER_CHANGE"))
    absolute = bambu
    arc_cmd = "G3" if bambu else "G2"
    out = [HEADER.rstrip("\n"), "M82" if absolute else "M83", "G90", "M104 S210", "G28"]
    e_total = 0.0

    def move_e(length: float) -> str:
        nonlocal e_total
        e = _e(length)
        e_total += e
        return f"{(e_total if absolute else e):.5f}"

    x0 = y0 = 20.0
    for layer in range(3):
        z = round(0.2 * (layer + 1), 3)
        out += [tags["layer"], f";Z:{z}" if not bambu else f"; Z_HEIGHT: {z}",
                tags["height"] + f"{HEIGHT}"]
        out.append(f"G0 X{x0 + R:.3f} Y{y0:.3f} Z{z:.3f} F9000")
        out += [tags["role"] + "Outer wall", tags["width"] + f"{WIDTH}"]
        # bottom edge, right edge, top edge, then a quarter arc closing the left side
        out.append(f"G1 X{x0 + SIDE:.3f} Y{y0:.3f} E{move_e(SIDE - R)} F3600")
        out.append(f"G1 X{x0 + SIDE:.3f} Y{y0 + SIDE:.3f} E{move_e(SIDE)}")
        out.append(f"G1 X{x0 + R:.3f} Y{y0 + SIDE:.3f} E{move_e(SIDE - R)}")
        # Corner arc from (x0+R, y0+SIDE) to (x0, y0+SIDE-R). The Bambu sample rounds the
        # corner (G3, counter-clockwise about (x0+R, y0+SIDE-R)); the plain sample uses G2
        # (clockwise) about (x0, y0+SIDE), a concave notch, so both arc directions are covered.
        if bambu:
            out.append(f"{arc_cmd} X{x0:.3f} Y{y0 + SIDE - R:.3f} I0.000 J{-R:.3f} "
                       f"E{move_e(math.pi * R / 2)}")
        else:
            out.append(f"{arc_cmd} X{x0:.3f} Y{y0 + SIDE - R:.3f} I{-R:.3f} J0.000 "
                       f"E{move_e(math.pi * R / 2)}")
        out.append(f"G1 X{x0:.3f} Y{y0:.3f} E{move_e(SIDE - R)}")
        out.append(f"G1 X{x0 + R:.3f} Y{y0:.3f} E{move_e(R)}")
        # one infill line, preceded by a retract / travel / unretract
        retract = 0.8
        out.append(f"G1 E{(e_total - retract) if absolute else -retract:.5f} F1800")
        out.append(f"G0 X{x0 + 3:.3f} Y{y0 + 3:.3f} F9000")
        out.append(f"G1 E{e_total if absolute else retract:.5f} F1800")
        out += [tags["role"] + "Sparse infill"]
        out.append(f"G1 X{x0 + 7:.3f} Y{y0 + 7:.3f} E{move_e(math.hypot(4, 4))} F6000")
    out += ["M104 S0", "; end of file", ""]
    return "\n".join(out)


def main() -> None:
    (HERE / "plain_square.gcode").write_text(build(bambu=False), encoding="utf-8", newline="\n")
    (HERE / "bambu_square.gcode").write_text(build(bambu=True), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
